# Generated by Django 4.0.1 on 2022-02-03 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('L', 'LOAD'), ('C', 'CREATE'), ('R', 'RESULTS')], default=('L', 'LOAD'), max_length=1)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(choices=[(1, 'EXATAS'), (2, 'BIOLÓGICAS'), (3, 'HUMANAS'), (4, 'ARTES'), (5, 'LETRAS')])),
                ('workload', models.PositiveSmallIntegerField(default=40)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('grade', models.PositiveSmallIntegerField()),
                ('subclass', models.CharField(max_length=2, null=True)),
                ('period', models.CharField(choices=[('M', 'MANHÃ'), ('T', 'TARDE'), ('N', 'NOITE')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('area', models.IntegerField(choices=[(1, 'EXATAS'), (2, 'BIOLÓGICAS'), (3, 'HUMANAS'), (4, 'ARTES'), (5, 'LETRAS')])),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('weekday', models.IntegerField(choices=[(2, 'Segunda-feira'), (3, 'Terça-feira'), (4, 'Quarta-feira'), (5, 'Quinta-feira'), (6, 'Sexta-feira')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period', models.CharField(choices=[('M', 'MANHÃ'), ('T', 'TARDE'), ('N', 'NOITE')], max_length=1, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distribution.distribution')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.professor')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.studentsclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.subject')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorScheduleOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'EM ANÁLISE'), ('A', 'ACEITO'), ('N', 'NEGADO')], max_length=1, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.professor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.schedule')),
            ],
        ),
    ]
